version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
    env_file: # Load environment variables from .env file
      - /keys/.prod-keys
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
